use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Language {
    Rust,
    Python,
    JavaScript,
    Jsx,
    TypeScript,
    Tsx,
    Go,
    Java,
    C,
    Cpp,
    Ruby,
    Shell,
    Kotlin,
    Swift,
    CSharp,
    Scala,
    PHP,
    Lua,
    Elixir,
    Haskell,
    OCaml,
    Zig,
    Dart,
    R,
    Perl,
    Toml,
    Yaml,
    Html,
    Css,
    Sql,
    Hcl,
    Nix,
    Clojure,
    Erlang,
    ObjC,
}

impl Language {
    pub fn from_extension(ext: &str) -> Option<Self> {
        match ext {
            "rs" => Some(Language::Rust),
            "py" | "pyi" => Some(Language::Python),
            "js" | "mjs" | "cjs" => Some(Language::JavaScript),
            "jsx" => Some(Language::Jsx),
            "ts" | "mts" | "cts" => Some(Language::TypeScript),
            "tsx" => Some(Language::Tsx),
            "go" => Some(Language::Go),
            "java" => Some(Language::Java),
            "c" | "h" => Some(Language::C),
            "cpp" | "cc" | "cxx" | "hpp" | "hxx" => Some(Language::Cpp),
            "rb" => Some(Language::Ruby),
            "sh" | "bash" | "zsh" => Some(Language::Shell),
            "kt" | "kts" => Some(Language::Kotlin),
            "swift" => Some(Language::Swift),
            "cs" => Some(Language::CSharp),
            "scala" | "sc" => Some(Language::Scala),
            "php" | "phtml" => Some(Language::PHP),
            "lua" => Some(Language::Lua),
            "ex" | "exs" => Some(Language::Elixir),
            "hs" => Some(Language::Haskell),
            "ml" | "mli" => Some(Language::OCaml),
            "zig" => Some(Language::Zig),
            "dart" => Some(Language::Dart),
            "r" | "R" => Some(Language::R),
            "pl" | "pm" => Some(Language::Perl),
            "toml" => Some(Language::Toml),
            "yml" | "yaml" => Some(Language::Yaml),
            "html" | "htm" => Some(Language::Html),
            "css" => Some(Language::Css),
            "sql" => Some(Language::Sql),
            "tf" | "hcl" => Some(Language::Hcl),
            "nix" => Some(Language::Nix),
            "clj" | "cljs" | "cljc" => Some(Language::Clojure),
            "erl" | "hrl" => Some(Language::Erlang),
            "m" => Some(Language::ObjC),
            _ => None,
        }
    }

    pub fn from_path(path: &Path) -> Option<Self> {
        path.extension()
            .and_then(|e| e.to_str())
            .and_then(Self::from_extension)
    }

    /// The .so file name to look for (e.g. "rust.so").
    /// JSX reuses javascript.so. All others match their grammar name.
    pub fn so_file_name(&self) -> &'static str {
        match self {
            Language::Rust => "rust.so",
            Language::Python => "python.so",
            Language::JavaScript | Language::Jsx => "javascript.so",
            Language::TypeScript => "typescript.so",
            Language::Tsx => "tsx.so",
            Language::Go => "go.so",
            Language::Java => "java.so",
            Language::C => "c.so",
            Language::Cpp => "cpp.so",
            Language::Ruby => "ruby.so",
            Language::Shell => "bash.so",
            Language::Kotlin => "kotlin.so",
            Language::Swift => "swift.so",
            Language::CSharp => "c-sharp.so",
            Language::Scala => "scala.so",
            Language::PHP => "php.so",
            Language::Lua => "lua.so",
            Language::Elixir => "elixir.so",
            Language::Haskell => "haskell.so",
            Language::OCaml => "ocaml.so",
            Language::Zig => "zig.so",
            Language::Dart => "dart.so",
            Language::R => "r.so",
            Language::Perl => "perl.so",
            Language::Toml => "toml.so",
            Language::Yaml => "yaml.so",
            Language::Html => "html.so",
            Language::Css => "css.so",
            Language::Sql => "sql.so",
            Language::Hcl => "hcl.so",
            Language::Nix => "nix.so",
            Language::Clojure => "clojure.so",
            Language::Erlang => "erlang.so",
            Language::ObjC => "objc.so",
        }
    }

    /// The C symbol exported by the grammar .so (e.g. "tree_sitter_rust").
    pub fn symbol_name(&self) -> &'static [u8] {
        match self {
            Language::Rust => b"tree_sitter_rust",
            Language::Python => b"tree_sitter_python",
            Language::JavaScript | Language::Jsx => b"tree_sitter_javascript",
            Language::TypeScript => b"tree_sitter_typescript",
            Language::Tsx => b"tree_sitter_tsx",
            Language::Go => b"tree_sitter_go",
            Language::Java => b"tree_sitter_java",
            Language::C => b"tree_sitter_c",
            Language::Cpp => b"tree_sitter_cpp",
            Language::Ruby => b"tree_sitter_ruby",
            Language::Shell => b"tree_sitter_bash",
            Language::Kotlin => b"tree_sitter_kotlin",
            Language::Swift => b"tree_sitter_swift",
            Language::CSharp => b"tree_sitter_c_sharp",
            Language::Scala => b"tree_sitter_scala",
            Language::PHP => b"tree_sitter_php",
            Language::Lua => b"tree_sitter_lua",
            Language::Elixir => b"tree_sitter_elixir",
            Language::Haskell => b"tree_sitter_haskell",
            Language::OCaml => b"tree_sitter_ocaml",
            Language::Zig => b"tree_sitter_zig",
            Language::Dart => b"tree_sitter_dart",
            Language::R => b"tree_sitter_r",
            Language::Perl => b"tree_sitter_perl",
            Language::Toml => b"tree_sitter_toml",
            Language::Yaml => b"tree_sitter_yaml",
            Language::Html => b"tree_sitter_html",
            Language::Css => b"tree_sitter_css",
            Language::Sql => b"tree_sitter_sql",
            Language::Hcl => b"tree_sitter_hcl",
            Language::Nix => b"tree_sitter_nix",
            Language::Clojure => b"tree_sitter_clojure",
            Language::Erlang => b"tree_sitter_erlang",
            Language::ObjC => b"tree_sitter_objc",
        }
    }

    /// The grammar name used in download URLs (e.g. "rust", "bash").
    pub fn grammar_name(&self) -> &'static str {
        match self {
            Language::Rust => "rust",
            Language::Python => "python",
            Language::JavaScript | Language::Jsx => "javascript",
            Language::TypeScript => "typescript",
            Language::Tsx => "tsx",
            Language::Go => "go",
            Language::Java => "java",
            Language::C => "c",
            Language::Cpp => "cpp",
            Language::Ruby => "ruby",
            Language::Shell => "bash",
            Language::Kotlin => "kotlin",
            Language::Swift => "swift",
            Language::CSharp => "c-sharp",
            Language::Scala => "scala",
            Language::PHP => "php",
            Language::Lua => "lua",
            Language::Elixir => "elixir",
            Language::Haskell => "haskell",
            Language::OCaml => "ocaml",
            Language::Zig => "zig",
            Language::Dart => "dart",
            Language::R => "r",
            Language::Perl => "perl",
            Language::Toml => "toml",
            Language::Yaml => "yaml",
            Language::Html => "html",
            Language::Css => "css",
            Language::Sql => "sql",
            Language::Hcl => "hcl",
            Language::Nix => "nix",
            Language::Clojure => "clojure",
            Language::Erlang => "erlang",
            Language::ObjC => "objc",
        }
    }

    /// All distinct grammar names (for fetch-parsers --all).
    pub fn all_grammar_names() -> &'static [&'static str] {
        &[
            "rust", "python", "javascript", "typescript", "tsx",
            "go", "java", "c", "cpp", "ruby", "bash",
            "kotlin", "swift", "c-sharp", "scala", "php",
            "lua", "elixir", "haskell", "ocaml", "zig", "dart",
            "r", "perl", "toml", "yaml", "html", "css", "sql",
            "hcl", "nix", "clojure", "erlang", "objc",
        ]
    }
}
